apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
stringData:
  databaseName: "Test1"
  rootPassword: "1234567"
  username: "a1"
  password: "b1"
  mysqlReadinessFile.sh: |
    mysql -uroot -p1234567 --protocol tcp -h 127.0.0.1 -e "SELECT 1"
  mysqlPing.sh: |
    mysqladmin -uroot -p1234567 ping